# Generated by Django 6.1 on 2026-08-11 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updates', '-created']},
        ),
    ]
